=== genjosanzo/galaxy-ce/core/src/main/resources/META-INF/galaxy-plugin-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.mulesource.org/schema/galaxy-plugin">

    <xs:import namespace="http://www.w3.org/XML/1998/namespace"/>

    <xs:element name="galaxy-plugin" type="galaxyPluginType"/>

    <xs:complexType name="columnType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:NMTOKEN" name="index-field"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="languagesType">
        <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="XQUERY"/>
            <xs:enumeration value="XPATH"/>
            <xs:enumeration value="GROOVY"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="galaxyPluginType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:NMTOKEN" name="class"/>
            <xs:element type="xs:string" name="description"/>
            <xs:element type="xs:string" name="content-type"/>
            <xs:element type="xs:string" name="small-icon"/>
            <xs:element type="xs:string" name="large-icon"/>
            <xs:element type="namespaceType" name="namespace"/>
            <xs:element type="indexesType" name="indexes"/>
            <xs:element type="viewsType" name="views"/>
            <xs:element type="policiesType" name="policies"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="indexesType">
        <xs:sequence>
            <xs:element type="indexType" name="index" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="indexType">
        <xs:sequence>
            <xs:element name="field-name" type="xs:NMTOKEN"/>
            <xs:element name="display-name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="language" type="languagesType"/>
            <xs:element name="search-input-type" type="xs:NMTOKEN"/>
            <xs:element name="expression" type="xs:string"/>
            <xs:element name="namespace" type="namespaceType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="policiesType">
        <xs:sequence>
            <xs:element type="policyType" name="policy"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="viewsType">
        <xs:sequence>
            <xs:element type="viewType" name="view"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="namespaceType">
        <xs:sequence>
            <xs:element name="prefix" maxOccurs="1" minOccurs="1"/>
            <xs:element type="xs:string" name="uri"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="policyType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="class"/>
            <xs:element type="xs:string" name="description"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="viewType">
        <xs:sequence>
            <xs:element type="columnType" name="column"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== genjosanzo/galaxy-ce/integration/mule1/src/main/resources/META-INF/galaxy-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<galaxy-plugin xmlns="http://www.mulesource.org/schema/galaxy-plugin"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
       http://www.mulesource.org/schema/galaxy-plugin http://www.mulesource.org/schema/galaxy-plugin/galaxy-plugin-1.0.xsd">

    <name>Mule Configurations</name>
    <class>org.mule.galaxy.impl.artifact.MuleArtifactPlugin</class>
    <description>Allows Mule 1 cofiguration files to be managed by Galaxy.  Users can register, query and view Mule 1 configuration files with this plugin.</description>
    <content-type>application/mule+xml</content-type>
    <small-icon>META-INF/images/mule1_16x16.png</small-icon>
    <large-icon>META-INF/images/mule1_32x32.png</large-icon>
    <namespace>
        <prefix>mule-configuration</prefix>
    </namespace>
    <indexes>
        <index>
            <field-name>mule.server.id</field-name>
            <display-name>Mule Server Id</display-name>
            <description>Indexes &lt;mule-configuration id&gt; attribute</description>
            <language>XQUERY</language>
            <search-input-type>java.lang.String</search-input-type>
            <expression><![CDATA[
                declare variable $document external;\n
                <values> {
                   for $e in $document/mule-configuration
                     return <value>{data($e/@id)}</value>
                   } </values>;
                   ]]>
            </expression>
            <namespace>
                <prefix>mule-configuration</prefix>
            </namespace>
        </index>
        <index>
            <field-name>mule.descriptor</field-name>
            <display-name>Mule Descriptors</display-name>
            <description>Indexes Mule 1 service descriptors</description>
            <language>XQUERY</language>
            <search-input-type>java.lang.String</search-input-type>
            <expression><![CDATA[
                declare variable $document external;\n
                <values> {
                   for $e in $document//mule-descriptor
                     return <value>{data($e/@name)}</value>
                   } </values>;
                   ]]>
            </expression>
            <namespace>
                <prefix>mule-configuration</prefix>
                <uri></uri>
            </namespace>
        </index>
    </indexes>
    <views>
        <view>
            <column>
                <name>Descriptors</name>
                <index-field>mule.descriptor</index-field>
            </column>
        </view>
    </views>
    <policies>
        <policy>
            <name>Require SSL</name>
            <class>org.mule.galaxy.policy.mule.RequireSSLPolicy</class>
            <description>Enforces the use of ssl on http and tcp endpoints</description>
        </policy>
    </policies>
</galaxy-plugin>
